### ISSUE TITLE
After lnd update - 2 channels went Status: not active

### ISSUE THREAD

**Issue by gtx1070rig** [openoms/lightning-node-management#14] opened 2021-02-07 19:18 UTC
I followed the guide:

https://github.com/openoms/lightning-node-management/blob/master/lnd.updates/README.md

updated to version v0.12.0-beta... after this i checked my channels and some are not going active anymore.... 

I am able to connect to this peers manualy but the peers are disappearing shortly after doing this....

 do i miss something? do i need to do anything or o i just need to wait some time?

i allready tried the follwing:

updated also bitcoin version to latest version (0.21)
updated raspblitz to latest version (1.63)
updated thunderhub to latest version (0.12.7)

but don'T think this was needed.....

**Comment by openoms** [comment] 2021-02-07 21:58
apart from restarting the node, connect to peers manually and waiting I cannot think of anything else. Are your peers online?
If LND updated without errors the issue is not related to the update script.

**Comment by gtx1070rig** [comment] 2021-02-08 05:44
So there seems to be any other other reasons for this?
An 3rd channel opened without problems.... Needed some days for confirmations but works fine...

Here some suspicious Logs?

```
2021-02-08 05:37:11.191 [DBG] LNWL: ChannelPoint(6b559fdf1c75c1b7ea7694a2a7a5c5d8809b7e618de35073b46c9284f54a2725:1): Restoring 0 dangling remote updates
2021-02-08 05:37:11.192 [DBG] LNWL: ChannelPoint(6b559fdf1c75c1b7ea7694a2a7a5c5d8809b7e618de35073b46c9284f54a2725:1): Restoring 0 local updates that the peer should sign
2021-02-08 05:37:11.192 [INF] PEER: NodeKey(03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601) loading ChannelPoint(6b559fdf1c75c1b7ea7694a2a7a5c5d8809b7e618de35073b46c9284f54a2725:1)
2021-02-08 05:37:11.193 [DBG] CNCT: New ChainEventSubscription(id=8) for ChannelPoint(6b559fdf1c75c1b7ea7694a2a7a5c5d8809b7e618de35073b46c9284f54a2725:1)
2021-02-08 05:37:11.193 [INF] HSWC: Removing channel link with ChannelID(25274af584926cb47350e38d617e9b80d8c5a5a7a29476eab7c1751cdf9f556a)
2021-02-08 05:37:11.193 [INF] HSWC: ChannelLink(667408:523:1): starting
2021-02-08 05:37:11.193 [INF] HSWC: Trimming open circuits for chan_id=667408:523:1, start_htlc_id=721
2021-02-08 05:37:11.193 [INF] HSWC: Adding live link chan_id=25274af584926cb47350e38d617e9b80d8c5a5a7a29476eab7c1751cdf9f556a, short_chan_id=667408:523:1
2021-02-08 05:37:11.193 [INF] PEER: Negotiated chan series queries with 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601
2021-02-08 05:37:11.193 [INF] DISC: Creating new GossipSyncer for peer=03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601
2021-02-08 05:37:11.193 [DBG] PEER: Sending NodeAnnouncement(node=036fc08fd3995afb7d2f55ff1837d59c5e226fc72fa09ec128ef5b60a6e8edb0ba, update_time=2021-02-08 05:31:44 +0000 GMT) to 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735
2021-02-08 05:37:11.194 [DBG] SRVR: Notifying that peer 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735 is online
2021-02-08 05:37:11.194 [DBG] DISC: Starting GossipSyncer(03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601)
2021-02-08 05:37:11.194 [DBG] DISC: GossipSyncer(03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601): state=chansSynced, type=PassiveSync
2021-02-08 05:37:11.207 [INF] HSWC: ChannelLink(667408:523:1): HTLC manager started, bandwidth=337679233 mSAT
2021-02-08 05:37:11.207 [INF] HSWC: ChannelLink(667408:523:1): attempting to re-resynchronize
2021-02-08 05:37:11.207 [DBG] PEER: Sending ChannelReestablish(next_local_height=1994, remote_tail_height=1995) to 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735
2021-02-08 05:37:11.193 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(6b559fdf1c75c1b7ea7694a2a7a5c5d8809b7e618de35073b46c9284f54a2725:1)
2021-02-08 05:37:11.211 [INF] PEER: unable to read message from 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735: EOF
2021-02-08 05:37:11.211 [INF] PEER: disconnecting 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735, reason: read handler closed
2021-02-08 05:37:11.312 [DBG] SRVR: Peer 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735 has been disconnected
2021-02-08 05:37:11.312 [DBG] FNDG: Cancelling all reservations for peer 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601
2021-02-08 05:37:11.312 [DBG] FNDG: No active reservations for node: 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601



2021-02-08 05:37:11.191 [DBG] LNWL: ChannelPoint(6b559fdf1c75c1b7ea7694a2a7a5c5d8809b7e618de35073b46c9284f54a2725:1): Restoring 0 dangling remote updates
2021-02-08 05:37:11.192 [DBG] LNWL: ChannelPoint(6b559fdf1c75c1b7ea7694a2a7a5c5d8809b7e618de35073b46c9284f54a2725:1): Restoring 0 local updates that the peer should sign
2021-02-08 05:37:11.192 [INF] PEER: NodeKey(03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601) loading ChannelPoint(6b559fdf1c75c1b7ea7694a2a7a5c5d8809b7e618de35073b46c9284f54a2725:1)
2021-02-08 05:37:11.193 [DBG] CNCT: New ChainEventSubscription(id=8) for ChannelPoint(6b559fdf1c75c1b7ea7694a2a7a5c5d8809b7e618de35073b46c9284f54a2725:1)
2021-02-08 05:37:11.193 [INF] HSWC: Removing channel link with ChannelID(25274af584926cb47350e38d617e9b80d8c5a5a7a29476eab7c1751cdf9f556a)
2021-02-08 05:37:11.193 [INF] HSWC: ChannelLink(667408:523:1): starting
2021-02-08 05:37:11.193 [INF] HSWC: Trimming open circuits for chan_id=667408:523:1, start_htlc_id=721
2021-02-08 05:37:11.193 [INF] HSWC: Adding live link chan_id=25274af584926cb47350e38d617e9b80d8c5a5a7a29476eab7c1751cdf9f556a, short_chan_id=667408:523:1
2021-02-08 05:37:11.193 [INF] PEER: Negotiated chan series queries with 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601
2021-02-08 05:37:11.193 [INF] DISC: Creating new GossipSyncer for peer=03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601
2021-02-08 05:37:11.193 [DBG] PEER: Sending NodeAnnouncement(node=036fc08fd3995afb7d2f55ff1837d59c5e226fc72fa09ec128ef5b60a6e8edb0ba, update_time=2021-02-08 05:31:44 +0000 GMT) to 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735
2021-02-08 05:37:11.194 [DBG] SRVR: Notifying that peer 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735 is online
2021-02-08 05:37:11.194 [DBG] DISC: Starting GossipSyncer(03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601)
2021-02-08 05:37:11.194 [DBG] DISC: GossipSyncer(03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601): state=chansSynced, type=PassiveSync
2021-02-08 05:37:11.207 [INF] HSWC: ChannelLink(667408:523:1): HTLC manager started, bandwidth=337679233 mSAT
2021-02-08 05:37:11.207 [INF] HSWC: ChannelLink(667408:523:1): attempting to re-resynchronize
2021-02-08 05:37:11.207 [DBG] PEER: Sending ChannelReestablish(next_local_height=1994, remote_tail_height=1995) to 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735
2021-02-08 05:37:11.193 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(6b559fdf1c75c1b7ea7694a2a7a5c5d8809b7e618de35073b46c9284f54a2725:1)
2021-02-08 05:37:11.211 [INF] PEER: unable to read message from 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735: EOF
2021-02-08 05:37:11.211 [INF] PEER: disconnecting 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735, reason: read handler closed
2021-02-08 05:37:11.312 [DBG] SRVR: Peer 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601@18.191.89.219:9735 has been disconnected
2021-02-08 05:37:11.312 [DBG] FNDG: Cancelling all reservations for peer 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601
2021-02-08 05:37:11.312 [DBG] FNDG: No active reservations for node: 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601


2021-02-08 05:37:11.312 [DBG] FNDG: Cancelling all reservations for peer 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601
2021-02-08 05:37:11.312 [DBG] FNDG: No active reservations for node: 03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601
2021-02-08 05:37:11.312 [INF] DISC: Removing GossipSyncer for peer=03c436af41160a355fc1ed230a64f6a64bcbd2ae50f12171d1318f9782602be601
2021-02-08 05:37:11.312 [INF] HSWC: Removing channel link with ChannelID(25274af584926cb47350e38d617e9b80d8c5a5a7a29476eab7c1751cdf9f556a)


2021-02-08 05:37:11.312 [INF] HSWC: ChannelLink(667408:523:1): stopping
2021-02-08 05:37:11.312 [WRN] HSWC: ChannelLink(667408:523:1): error when syncing channel states: link shutting down
2021-02-08 05:37:11.312 [DBG] HSWC: ChannelLink(667408:523:1): unable to sync channel states, link is shutting down
2021-02-08 05:37:11.312 [INF] HSWC: ChannelLink(667408:523:1): exited
```

**Comment by openoms** [comment] 2021-02-08 18:17
I am not sure if there is anything relevant in the logs. Would suggest to ask at the LND Developer Slack, you can find the link for it here: https://dev.lightning.community/

**Comment by gtx1070rig** [comment] 2021-02-08 18:27
> I am not sure if there is anything relevant in the logs. Would suggest to ask at the LND Developer Slack, you can find the link for it here: https://dev.lightning.community/

They also have no idea... i shuld close channels... but they have most of balance on remote site....

**Comment by gtx1070rig** [comment] 2021-02-09 04:09
``
2021-02-09 04:03:57.518 [INF] HSWC: Adding live link chan_id=5b349e3ef1d68757dcd944c0bffe48f8c862a1b089f8227c6933d4f05229945f, short_chan_id=668316:1253:1
2021-02-09 04:03:57.518 [INF] CNCT: Attempting to update ContractSignals for ChannelPoint(5e942952f0d433697c22f889b0a162c8f848febfc044d9dc5787d6f13e9e345b:1)
2021-02-09 04:03:57.518 [INF] HSWC: ChannelLink(668316:1253:1): HTLC manager started, bandwidth=954426881 mSAT
2021-02-09 04:03:57.518 [INF] HSWC: ChannelLink(668316:1253:1): attempting to re-resynchronize
2021-02-09 04:03:57.518 [INF] PEER: Negotiated chan series queries with 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf
2021-02-09 04:03:57.519 [INF] DISC: Creating new GossipSyncer for peer=03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf
2021-02-09 04:03:57.519 [DBG] DISC: Starting GossipSyncer(03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf)
2021-02-09 04:03:57.519 [DBG] DISC: GossipSyncer(03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf): state=chansSynced, type=PassiveSync
2021-02-09 04:03:57.518 [DBG] SRVR: **Notifying that peer 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735 is online**
2021-02-09 04:03:57.518 [DBG] PEER: Sending NodeAnnouncement(node=036fc08fd3995afb7d2f55ff1837d59c5e226fc72fa09ec128ef5b60a6e8edb0ba, update_time=2021-02-08 18:30:25 +0000 GMT) to 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735
2021-02-09 04:03:57.519 [INF] PEER: **unable to read message from 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735: EOF**
2021-02-09 04:03:57.519 [INF] PEER: **disconnecting** 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735, **reason: read handler closed**
2021-02-09 04:03:57.519 [DBG] PEER: Sending ChannelReestablish(next_local_height=5360, remote_tail_height=5360) to 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735
2021-02-09 04:03:57.520 [WRN] HSWC: ChannelLink(668316:1253:1): **error when syncing channel states: unable to send chan sync message** for ChannelPoint(5e942952f0d433697c22f889b0a162c8f848febfc044d9dc5787d6f13e9e345b:1): **peer exiting**
2021-02-09 04:03:57.520 [ERR] HSWC: ChannelLink(668316:1253:1): failing link: unable to synchronize channel states: unable to send chan sync message for ChannelPoint(5e942952f0d433697c22f889b0a162c8f848febfc044d9dc5787d6f13e9e345b:1): **peer exiting with error: unable to resume channel, recovery required**
2021-02-09 04:03:57.520 [INF] HSWC: ChannelLink(668316:1253:1): exited
2021-02-09 04:03:57.620 [DBG] SRVR: Peer 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735 has been disconnected
2021-02-09 04:03:57.620 [DBG] FNDG: Cancelling all reservations for peer 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf
2021-02-09 04:03:57.620 [DBG] FNDG: No active reservations for node: 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf
2021-02-09 04:03:57.620 [INF] DISC: Removing GossipSyncer for peer=03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf
2021-02-09 04:03:57.620 [INF] HSWC: Removing channel link with ChannelID(5b349e3ef1d68757dcd944c0bffe48f8c862a1b089f8227c6933d4f05229945f)
2021-02-09 04:03:57.620 [INF] HSWC: ChannelLink(668316:1253:1): stopping
2021-02-09 04:03:57.620 [DBG] SRVR: Notifying that peer 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735 is offline
2021-02-09 04:03:57.620 [DBG] SRVR: removing peer 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735
2021-02-09 04:03:57.620 [DBG] PRNF: PeerNotifier notifying peer: 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf offline
2021-02-09 04:03:57.621 [DBG] SRVR: Scheduling connection re-establishment to persistent peer 03634bda49c9c42afd876d8288802942c49e58fbec3844ff54b46143bfcb6cdfaf@157.230.144.234:9735 in 1h3m0s
``

**Comment by openoms** [comment] 2021-02-09 10:44
It should be possible to force close the channel, but it will incur a high fee for the peer who opened it.

**Comment by gtx1070rig** [comment] 2021-02-09 16:08
> It should be possible to force close the channel, but it will incur a high fee for the peer who opened it.

But i will lose my remote balance dont I ?!

**Comment by openoms** [comment] 2021-02-10 17:04
The remote balance is remote because it is not yours. 
You only loose the closing fee (if you opened the channel) and the incoming liquidity (not your balance.)

**Comment by gtx1070rig** [comment] 2021-02-12 03:53
> The remote balance is remote because it is not yours.
> You only loose the closing fee (if you opened the channel) and the incoming liquidity (not your balance.)

I balanced this channel.... so remote is goin to node partner...  or how i can get this balance?

**Comment by openoms** [comment] 2021-02-12 09:31
You can try rebalancing into it and then close, but only if online.
If the channel is offline you can't change the balance on it.
Will close this since not actionable in this guide.
For general LN questions see the LND Slack, IRC or
https://t.me/lightning_network

**Closed** 2021-02-12 09:31 UTC
